/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RecipeSummary } from "./types";
export { RecipeSummary } from "./types";
export namespace Components {
    interface RcEmptyState {
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default ''
         */
        "message": string;
    }
    interface RcFilterChip {
        /**
          * @default false
         */
        "active": boolean;
        /**
          * @default ''
         */
        "label": string;
    }
    interface RcModal {
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default false
         */
        "open": boolean;
    }
    interface RcRecipeCard {
        /**
          * @default false
         */
        "isFavorite": boolean;
        "recipe": RecipeSummary;
    }
    interface RcSearchBar {
        /**
          * @default 300
         */
        "debounce": number;
        /**
          * @default 'Search recipes...'
         */
        "placeholder": string;
        /**
          * @default ''
         */
        "value": string;
    }
}
export interface RcFilterChipCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRcFilterChipElement;
}
export interface RcModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRcModalElement;
}
export interface RcRecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRcRecipeCardElement;
}
export interface RcSearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRcSearchBarElement;
}
declare global {
    interface HTMLRcEmptyStateElement extends Components.RcEmptyState, HTMLStencilElement {
    }
    var HTMLRcEmptyStateElement: {
        prototype: HTMLRcEmptyStateElement;
        new (): HTMLRcEmptyStateElement;
    };
    interface HTMLRcFilterChipElementEventMap {
        "chiptoggle": { label: string; active: boolean };
    }
    interface HTMLRcFilterChipElement extends Components.RcFilterChip, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRcFilterChipElementEventMap>(type: K, listener: (this: HTMLRcFilterChipElement, ev: RcFilterChipCustomEvent<HTMLRcFilterChipElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRcFilterChipElementEventMap>(type: K, listener: (this: HTMLRcFilterChipElement, ev: RcFilterChipCustomEvent<HTMLRcFilterChipElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRcFilterChipElement: {
        prototype: HTMLRcFilterChipElement;
        new (): HTMLRcFilterChipElement;
    };
    interface HTMLRcModalElementEventMap {
        "modalclose": void;
    }
    interface HTMLRcModalElement extends Components.RcModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRcModalElementEventMap>(type: K, listener: (this: HTMLRcModalElement, ev: RcModalCustomEvent<HTMLRcModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRcModalElementEventMap>(type: K, listener: (this: HTMLRcModalElement, ev: RcModalCustomEvent<HTMLRcModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRcModalElement: {
        prototype: HTMLRcModalElement;
        new (): HTMLRcModalElement;
    };
    interface HTMLRcRecipeCardElementEventMap {
        "cardselect": string;
        "favoritetoggle": string;
    }
    interface HTMLRcRecipeCardElement extends Components.RcRecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRcRecipeCardElementEventMap>(type: K, listener: (this: HTMLRcRecipeCardElement, ev: RcRecipeCardCustomEvent<HTMLRcRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRcRecipeCardElementEventMap>(type: K, listener: (this: HTMLRcRecipeCardElement, ev: RcRecipeCardCustomEvent<HTMLRcRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRcRecipeCardElement: {
        prototype: HTMLRcRecipeCardElement;
        new (): HTMLRcRecipeCardElement;
    };
    interface HTMLRcSearchBarElementEventMap {
        "searchchange": string;
    }
    interface HTMLRcSearchBarElement extends Components.RcSearchBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRcSearchBarElementEventMap>(type: K, listener: (this: HTMLRcSearchBarElement, ev: RcSearchBarCustomEvent<HTMLRcSearchBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRcSearchBarElementEventMap>(type: K, listener: (this: HTMLRcSearchBarElement, ev: RcSearchBarCustomEvent<HTMLRcSearchBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRcSearchBarElement: {
        prototype: HTMLRcSearchBarElement;
        new (): HTMLRcSearchBarElement;
    };
    interface HTMLElementTagNameMap {
        "rc-empty-state": HTMLRcEmptyStateElement;
        "rc-filter-chip": HTMLRcFilterChipElement;
        "rc-modal": HTMLRcModalElement;
        "rc-recipe-card": HTMLRcRecipeCardElement;
        "rc-search-bar": HTMLRcSearchBarElement;
    }
}
declare namespace LocalJSX {
    interface RcEmptyState {
        /**
          * @default ''
         */
        "heading"?: string;
        /**
          * @default ''
         */
        "message"?: string;
    }
    interface RcFilterChip {
        /**
          * @default false
         */
        "active"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        "onChiptoggle"?: (event: RcFilterChipCustomEvent<{ label: string; active: boolean }>) => void;
    }
    interface RcModal {
        /**
          * @default ''
         */
        "heading"?: string;
        "onModalclose"?: (event: RcModalCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface RcRecipeCard {
        /**
          * @default false
         */
        "isFavorite"?: boolean;
        "onCardselect"?: (event: RcRecipeCardCustomEvent<string>) => void;
        "onFavoritetoggle"?: (event: RcRecipeCardCustomEvent<string>) => void;
        "recipe": RecipeSummary;
    }
    interface RcSearchBar {
        /**
          * @default 300
         */
        "debounce"?: number;
        "onSearchchange"?: (event: RcSearchBarCustomEvent<string>) => void;
        /**
          * @default 'Search recipes...'
         */
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }

    interface RcEmptyStateAttributes {
        "heading": string;
        "message": string;
    }
    interface RcFilterChipAttributes {
        "label": string;
        "active": boolean;
    }
    interface RcModalAttributes {
        "open": boolean;
        "heading": string;
    }
    interface RcRecipeCardAttributes {
        "isFavorite": boolean;
    }
    interface RcSearchBarAttributes {
        "value": string;
        "placeholder": string;
        "debounce": number;
    }

    interface IntrinsicElements {
        "rc-empty-state": Omit<RcEmptyState, keyof RcEmptyStateAttributes> & { [K in keyof RcEmptyState & keyof RcEmptyStateAttributes]?: RcEmptyState[K] } & { [K in keyof RcEmptyState & keyof RcEmptyStateAttributes as `attr:${K}`]?: RcEmptyStateAttributes[K] } & { [K in keyof RcEmptyState & keyof RcEmptyStateAttributes as `prop:${K}`]?: RcEmptyState[K] };
        "rc-filter-chip": Omit<RcFilterChip, keyof RcFilterChipAttributes> & { [K in keyof RcFilterChip & keyof RcFilterChipAttributes]?: RcFilterChip[K] } & { [K in keyof RcFilterChip & keyof RcFilterChipAttributes as `attr:${K}`]?: RcFilterChipAttributes[K] } & { [K in keyof RcFilterChip & keyof RcFilterChipAttributes as `prop:${K}`]?: RcFilterChip[K] };
        "rc-modal": Omit<RcModal, keyof RcModalAttributes> & { [K in keyof RcModal & keyof RcModalAttributes]?: RcModal[K] } & { [K in keyof RcModal & keyof RcModalAttributes as `attr:${K}`]?: RcModalAttributes[K] } & { [K in keyof RcModal & keyof RcModalAttributes as `prop:${K}`]?: RcModal[K] };
        "rc-recipe-card": Omit<RcRecipeCard, keyof RcRecipeCardAttributes> & { [K in keyof RcRecipeCard & keyof RcRecipeCardAttributes]?: RcRecipeCard[K] } & { [K in keyof RcRecipeCard & keyof RcRecipeCardAttributes as `attr:${K}`]?: RcRecipeCardAttributes[K] } & { [K in keyof RcRecipeCard & keyof RcRecipeCardAttributes as `prop:${K}`]?: RcRecipeCard[K] };
        "rc-search-bar": Omit<RcSearchBar, keyof RcSearchBarAttributes> & { [K in keyof RcSearchBar & keyof RcSearchBarAttributes]?: RcSearchBar[K] } & { [K in keyof RcSearchBar & keyof RcSearchBarAttributes as `attr:${K}`]?: RcSearchBarAttributes[K] } & { [K in keyof RcSearchBar & keyof RcSearchBarAttributes as `prop:${K}`]?: RcSearchBar[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rc-empty-state": LocalJSX.IntrinsicElements["rc-empty-state"] & JSXBase.HTMLAttributes<HTMLRcEmptyStateElement>;
            "rc-filter-chip": LocalJSX.IntrinsicElements["rc-filter-chip"] & JSXBase.HTMLAttributes<HTMLRcFilterChipElement>;
            "rc-modal": LocalJSX.IntrinsicElements["rc-modal"] & JSXBase.HTMLAttributes<HTMLRcModalElement>;
            "rc-recipe-card": LocalJSX.IntrinsicElements["rc-recipe-card"] & JSXBase.HTMLAttributes<HTMLRcRecipeCardElement>;
            "rc-search-bar": LocalJSX.IntrinsicElements["rc-search-bar"] & JSXBase.HTMLAttributes<HTMLRcSearchBarElement>;
        }
    }
}
